#!/bin/bash

echo "🚀 Quick Deploy - School Management System"
echo "=========================================="

echo ""
echo "📋 Pre-Deployment Checklist:"
echo "============================"
echo "1. ✅ Code is on GitHub: https://github.com/ankush-rana-03/Sms"
echo "2. ✅ render.yaml configuration ready"
echo "3. ⏳ Set up MongoDB Atlas (free)"
echo "4. ⏳ Set up Cloudinary (free)"
echo "5. ⏳ Create Render.com account"
echo ""

echo "🔗 Quick Setup Links:"
echo "====================="
echo "• MongoDB Atlas: https://www.mongodb.com/atlas"
echo "• Cloudinary: https://cloudinary.com/"
echo "• Render.com: https://render.com"
echo ""

echo "📝 Deployment Steps:"
echo "==================="
echo "1. Go to https://render.com"
echo "2. Sign up with GitHub"
echo "3. Click 'New +' → 'Blueprint'"
echo "4. Connect repo: ankush-rana-03/Sms"
echo "5. Set environment variables (see below)"
echo "6. Deploy!"
echo ""

echo "🔧 Required Environment Variables:"
echo "================================="
echo ""
echo "Backend Variables:"
echo "NODE_ENV=production"
echo "MONGODB_URI=mongodb+srv://username:password@cluster.mongodb.net/school_management"
echo "JWT_SECRET=your-super-secret-jwt-key-here"
echo "JWT_EXPIRE=7d"
echo "JWT_COOKIE_EXPIRE=7"
echo "FRONTEND_URL=https://your-frontend-app.onrender.com"
echo "CLOUDINARY_CLOUD_NAME=your-cloud-name"
echo "CLOUDINARY_API_KEY=your-api-key"
echo "CLOUDINARY_API_SECRET=your-api-secret"
echo "EMAIL_HOST=smtp.gmail.com"
echo "EMAIL_PORT=587"
echo "EMAIL_USER=your-email@gmail.com"
echo "EMAIL_PASS=your-app-password"
echo "FROM_NAME=School Management System"
echo "FROM_EMAIL=your-email@gmail.com"
echo ""
echo "Frontend Variables:"
echo "REACT_APP_API_URL=https://your-backend-app.onrender.com/api"
echo ""

echo "🎯 Your GitHub Repository:"
echo "https://github.com/ankush-rana-03/Sms"
echo ""

echo "📖 Full deployment guide: DEPLOYMENT.md"
echo ""

echo "🚀 Ready to deploy! Follow the steps above."